### ISSUE TITLE
Add reference to Chip Tool's upstream docs

### ISSUE THREAD

**Issue by farshidtz** [canonical/matter-docs#32]
Docs: https://project-chip.github.io/connectedhomeip-doc/guides/chip_tool_guide.html

---
*Reported from: https://canonical-matter.readthedocs-hosted.com/en/latest/how-to/chip-tool-commission-and-control/*

**Comment by jpm-canonical** [comment]
https://github.com/canonical/matter-docs/blob/f580f78f3e16f96eecb4292e098e1b6f55f13ca0/how-to/chip-tool-commission-and-control.rst?plain=1#L152

In the last paragraph of the Chip Tool Commission and Control doc, we link to: 
https://github.com/project-chip/connectedhomeip/blob/master/docs/guides/chip_tool_guide.md#using-chip-tool-for-matter-device-testing

We can do a simple replacement of the URL to the formatted docs on Github:
https://project-chip.github.io/connectedhomeip-doc/guides/chip_tool_guide.html#using-chip-tool-for-matter-device-testing

**Comment by farshidtz** [comment]
Makes sense to replace. I hadn't seen the link at the end.

**Comment by farshidtz** [comment]
Fixed via #36
